### ISSUE TITLE
open事件不相应

### ISSUE THREAD

**Issue by fengmumu1** [flarestart/egg-websocket-plugin#12]
![image](https://user-images.githubusercontent.com/37215225/124251939-0eb13980-db59-11eb-9ecf-7f60d91f5446.png)
如图，应该是先open再获取信息，但是 获取信息相应了open没有响应

**Comment by flarestart** [comment]
@fengmumu1  ，插件的逻辑是 WebSocket 连接成功后，也就是 open 触发以后，才会进入到 index 的逻辑里面，因此只需要在 index 函数内直接执行这个阶段的代码即可。

**Comment by fengmumu1** [comment]
> 阶段

那也就是说使用了插件的话其实就没有open这个事件了，因为插件的执行其实是在open了之后，后面有时间我给你提代码把这个钩子搞出来好不好呀
